### ISSUE TITLE
Not loggin in

### ISSUE THREAD

**Issue by Sensaicraft** [Chaosdave34/MCP-Snippets#1]
I did everything like described for my 1.8 Client and when I start the Client the Weblogin opens and I login but then nothing happens and I´m still Player + Random Number in the Client and there also doesn´t comes a message where it says I logged in in the Logs

**Comment by Chaosdave34** [comment]
Until now, there is no log message. But I will implement that.
The webpage should tell you that the login is done and that you can close the page. 
Could you try to join a server?

**Comment by Sensaicraft** [comment]
The webpage told me that but when i want to join a Server there comes a NullPointer Exception and when i join in single Player I´m just a Player + Random Number

**Comment by Chaosdave34** [comment]
Can you send me the lines of your code, where you create an authenticator object and call the login method?

**Comment by Sensaicraft** [comment]
Sorry for the late reply,

I create the Authenticator object and call the login method in my start method:

```
    public void startup() {
        FileManager.init();
        SplashProgress.setProgress(1, name + " - Starting DiscordRPC");
        discord.start();
        System.out.println("Started " + name + " in version " + version + " for Minecraft 1.8");
        EventManger.register(this);
        MicrosoftAuthenticator authenticator = new MicrosoftAuthenticator("c3e6769c-a580-4741-a9ed-a565fc4364af", "095a17a2-17be-4cf5-93c6-813774cff6c4");
        authenticator.login();
    }
```

and that method gets called in the Minecraft.java located startGame method

**Comment by Chaosdave34** [comment]
I have deleted your comment because it containd your azure id and secret key, with which everyone could access your Azure account.

It seems, that your clientSecret has a wrong format. My guess is, that you copied the wrong value.

**Comment by Sensaicraft** [comment]
Oh I copied the Secret ID and not the Value thats only there after the creation. It works now thank you.
(Sorry for that dumb mistake, I had some problems because the site wasn´t english for me because its not my native language)
